#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.datacoper.appprodutor.Resource", IsApplication=true)]

namespace com.datacoper.appprodutor
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int color_darkgreen_clover = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int color_green_clover = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int cor_button_login_bg = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int cor_button_login_bg_focus = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int cor_button_login_text = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int cor_principal_crm = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cor_principal_opacity_60_crm = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cor_secundaria_crm = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int cor_secundaria_opacity_10_crm = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int cor_secundaria_opacity_30_crm = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int cor_secundaria_opacity_60_crm = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int cor_select_selecionar = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int cor_success = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int cor_success_80 = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int orange_color = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int red_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int white_color = 2131034127;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int activity_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int activity_vertical_margin = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int list_padding = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int navigation_drawer_width = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int padding_division = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int padding_tela = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int shadow_width = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int slidingmenu_offset = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_sign_login = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int footer_repeat = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int header_gradient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_form_edittext_search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher_splash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_agenda = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_cotacao = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_noticias = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_pedidos = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_previsaotempo = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0007
			public const int footer = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int header = 2131361798;
			
			// aapt resource value: 0x7f0a0029
			public const int imageView1 = 2131361833;
			
			// aapt resource value: 0x7f0a000a
			public const int ovBT_Entrar = 2131361802;
			
			// aapt resource value: 0x7f0a000c
			public const int ovCB_MeLembrar = 2131361804;
			
			// aapt resource value: 0x7f0a0009
			public const int ovET_Senha = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int ovET_Usuario = 2131361800;
			
			// aapt resource value: 0x7f0a0026
			public const int ovIB_Clima = 2131361830;
			
			// aapt resource value: 0x7f0a0022
			public const int ovIB_Cotacao = 2131361826;
			
			// aapt resource value: 0x7f0a0027
			public const int ovIB_Noticias = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int ovIB_NoticiasInternas = 2131361832;
			
			// aapt resource value: 0x7f0a0024
			public const int ovIB_Pedido = 2131361828;
			
			// aapt resource value: 0x7f0a0023
			public const int ovIB_xx3 = 2131361827;
			
			// aapt resource value: 0x7f0a0025
			public const int ovLL_Clima = 2131361829;
			
			// aapt resource value: 0x7f0a0000
			public const int ovLL_Tudo = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int ovLV_Cotacao = 2131361793;
			
			// aapt resource value: 0x7f0a000f
			public const int ovLV_Noticia = 2131361807;
			
			// aapt resource value: 0x7f0a0012
			public const int ovLV_Pedido = 2131361810;
			
			// aapt resource value: 0x7f0a001e
			public const int ovLV_PrevisaoTempo = 2131361822;
			
			// aapt resource value: 0x7f0a0011
			public const int ovTV_Autor = 2131361809;
			
			// aapt resource value: 0x7f0a000b
			public const int ovTV_Cadastrar = 2131361803;
			
			// aapt resource value: 0x7f0a0021
			public const int ovTV_Condicoes = 2131361825;
			
			// aapt resource value: 0x7f0a000e
			public const int ovTV_Conteudo = 2131361806;
			
			// aapt resource value: 0x7f0a0010
			public const int ovTV_Data = 2131361808;
			
			// aapt resource value: 0x7f0a0005
			public const int ovTV_DataCotacao = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int ovTV_Descricao = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int ovTV_IdProduto = 2131361794;
			
			// aapt resource value: 0x7f0a001f
			public const int ovTV_Local = 2131361823;
			
			// aapt resource value: 0x7f0a0013
			public const int ovTV_NumeroPedido = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int ovTV_Produto = 2131361813;
			
			// aapt resource value: 0x7f0a001c
			public const int ovTV_Produtor = 2131361820;
			
			// aapt resource value: 0x7f0a0014
			public const int ovTV_Quantidade = 2131361812;
			
			// aapt resource value: 0x7f0a001b
			public const int ovTV_QuantidadeAFaturar = 2131361819;
			
			// aapt resource value: 0x7f0a0018
			public const int ovTV_QuantidadeFaturada = 2131361816;
			
			// aapt resource value: 0x7f0a001d
			public const int ovTV_Status = 2131361821;
			
			// aapt resource value: 0x7f0a0020
			public const int ovTV_TemperaturaMaxima = 2131361824;
			
			// aapt resource value: 0x7f0a000d
			public const int ovTV_Titulo = 2131361805;
			
			// aapt resource value: 0x7f0a001a
			public const int ovTV_ValorAFaturar = 2131361818;
			
			// aapt resource value: 0x7f0a0004
			public const int ovTV_ValorCotacao = 2131361796;
			
			// aapt resource value: 0x7f0a0019
			public const int ovTV_ValorFatudaro = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int ovTV_ValorTotal = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int ovTV_ValorUnitario = 2131361814;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int num_cols = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Cotacao = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CotacaoTemplate = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int NoticiaInternaTemplate = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Noticias = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int NoticiaTemplate = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Pedido = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int PedidoTemplate = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int PrevisaoTempo = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int PrevisaoTempoTemplate = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Principal = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Splash = 2130968587;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher_splash = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_logo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_menu_agenda = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_menu_cotacao = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_menu_noticias = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_menu_pedidos = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ic_menu_previsaotempo = 2130903046;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int AppTheme_Login = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int AppTheme_Login_Image = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int AppTheme_NoTitleBar = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int AppTheme_SplashScreen = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int AutoCompleteTextView = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int Button = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int Button_Login = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int CheckBox = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int CustomActionBar = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int Dashboard = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int Dashboard_Button = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int Dashboard_Layout = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int Dashboard_Layout_Grid = 2131296272;
			
			// aapt resource value: 0x7f090009
			public const int EditText = 2131296265;
			
			// aapt resource value: 0x7f090006
			public const int EditText_Login = 2131296262;
			
			// aapt resource value: 0x7f090012
			public const int Form = 2131296274;
			
			// aapt resource value: 0x7f090022
			public const int Form_AutoCompleteTextView = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int Form_Button = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int Form_Division = 2131296292;
			
			// aapt resource value: 0x7f090020
			public const int Form_EditText_Icon = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int Form_EditText_Multiple = 2131296287;
			
			// aapt resource value: 0x7f090021
			public const int Form_EditText_Search = 2131296289;
			
			// aapt resource value: 0x7f09001e
			public const int Form_EditText_Single = 2131296286;
			
			// aapt resource value: 0x7f09002c
			public const int Form_FixNoAutoFocus = 2131296300;
			
			// aapt resource value: 0x7f090029
			public const int Form_GPS = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int Form_GPS_Icon = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int Form_GPS_Label = 2131296299;
			
			// aapt resource value: 0x7f090017
			public const int Form_Group = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int Form_Group_Last = 2131296280;
			
			// aapt resource value: 0x7f090013
			public const int Form_Layout = 2131296275;
			
			// aapt resource value: 0x7f090025
			public const int Form_ListEmpty = 2131296293;
			
			// aapt resource value: 0x7f090027
			public const int Form_ListEmpty_Image = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int Form_ListEmpty_Padding = 2131296294;
			
			// aapt resource value: 0x7f090028
			public const int Form_ListEmpty_Text = 2131296296;
			
			// aapt resource value: 0x7f090014
			public const int Form_Row = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int Form_Row_Padding = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int Form_Row_Padding_Line = 2131296278;
			
			// aapt resource value: 0x7f09001c
			public const int Form_TextView_Info = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int Form_TextView_Info_Padding = 2131296285;
			
			// aapt resource value: 0x7f090019
			public const int Form_TextView_Label = 2131296281;
			
			// aapt resource value: 0x7f09001b
			public const int Form_TextView_SubTitle = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int Form_TextView_Title = 2131296282;
			
			// aapt resource value: 0x7f09002d
			public const int Page = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int Page_Layout = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int Page_Layout_Padding = 2131296303;
			
			// aapt resource value: 0x7f090031
			public const int Page_ListView = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int Page_ListView_Group = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int Page_ListView_Template = 2131296307;
			
			// aapt resource value: 0x7f090035
			public const int Page_ListView_Template_Group = 2131296309;
			
			// aapt resource value: 0x7f090036
			public const int Page_ListView_Template_Icon = 2131296310;
			
			// aapt resource value: 0x7f09003b
			public const int Page_ListView_Template_Label_LeftInfo_Size_14dp = 2131296315;
			
			// aapt resource value: 0x7f090039
			public const int Page_ListView_Template_Label_RightInfo = 2131296313;
			
			// aapt resource value: 0x7f09003d
			public const int Page_ListView_Template_Label_RightInfo_Label = 2131296317;
			
			// aapt resource value: 0x7f09003a
			public const int Page_ListView_Template_Label_RightInfo_Size_14dp = 2131296314;
			
			// aapt resource value: 0x7f09003c
			public const int Page_ListView_Template_Label_RightInfoDefault = 2131296316;
			
			// aapt resource value: 0x7f090038
			public const int Page_ListView_Template_Label_SubTitle = 2131296312;
			
			// aapt resource value: 0x7f090037
			public const int Page_ListView_Template_Label_Title = 2131296311;
			
			// aapt resource value: 0x7f090034
			public const int Page_ListView_Template_Row = 2131296308;
			
			// aapt resource value: 0x7f09003e
			public const int Page_Seletor_Row = 2131296318;
			
			// aapt resource value: 0x7f090030
			public const int Page_TextView = 2131296304;
			
			// aapt resource value: 0x7f09000b
			public const int RadioButton = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int TextView = 2131296264;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
